
    


---
apiVersion: v1
kind: Service
metadata:
  
  name: quorum-node1
  labels:
    app: qubernetes
    tier: backend
    name: quorum-node1
spec:
  selector:
    app: qubernetes
    tier: backend
    name: quorum-node1-deployment
  # NodePort | ClusterIP
  type: ClusterIP
  ports:
    - name: tm-manager 
      protocol: TCP
      port: 9001
      targetPort: 9001
    # default 8545
    - name: tm-tessera-third-part
      protocol: TCP
      port: 9080
      targetPort: 9080
    # default 8545
    - name: wsrpc-listener
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: quorum-listener
      protocol: TCP
      port: 21000
      targetPort: 21000
    - name: raft
      protocol: TCP
      targetPort: 50401
      port: 50401
    


---
apiVersion: v1
kind: Service
metadata:
  
  name: quorum-node2
  labels:
    app: qubernetes
    tier: backend
    name: quorum-node2
spec:
  selector:
    app: qubernetes
    tier: backend
    name: quorum-node2-deployment
  # NodePort | ClusterIP
  type: ClusterIP
  ports:
    - name: tm-manager 
      protocol: TCP
      port: 9001
      targetPort: 9001
    # default 8545
    - name: tm-tessera-third-part
      protocol: TCP
      port: 9080
      targetPort: 9080
    # default 8545
    - name: wsrpc-listener
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: quorum-listener
      protocol: TCP
      port: 21000
      targetPort: 21000
    - name: raft
      protocol: TCP
      targetPort: 50401
      port: 50401
    


---
apiVersion: v1
kind: Service
metadata:
  
  name: quorum-node3
  labels:
    app: qubernetes
    tier: backend
    name: quorum-node3
spec:
  selector:
    app: qubernetes
    tier: backend
    name: quorum-node3-deployment
  # NodePort | ClusterIP
  type: ClusterIP
  ports:
    - name: tm-manager 
      protocol: TCP
      port: 9001
      targetPort: 9001
    # default 8545
    - name: tm-tessera-third-part
      protocol: TCP
      port: 9080
      targetPort: 9080
    # default 8545
    - name: wsrpc-listener
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: quorum-listener
      protocol: TCP
      port: 21000
      targetPort: 21000
    - name: raft
      protocol: TCP
      targetPort: 50401
      port: 50401
    


---
apiVersion: v1
kind: Service
metadata:
  
  name: quorum-node4
  labels:
    app: qubernetes
    tier: backend
    name: quorum-node4
spec:
  selector:
    app: qubernetes
    tier: backend
    name: quorum-node4-deployment
  # NodePort | ClusterIP
  type: ClusterIP
  ports:
    - name: tm-manager 
      protocol: TCP
      port: 9001
      targetPort: 9001
    # default 8545
    - name: tm-tessera-third-part
      protocol: TCP
      port: 9080
      targetPort: 9080
    # default 8545
    - name: wsrpc-listener
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: quorum-listener
      protocol: TCP
      port: 21000
      targetPort: 21000
    - name: raft
      protocol: TCP
      targetPort: 50401
      port: 50401
    


---
apiVersion: v1
kind: Service
metadata:
  
  name: quorum-node5
  labels:
    app: qubernetes
    tier: backend
    name: quorum-node5
spec:
  selector:
    app: qubernetes
    tier: backend
    name: quorum-node5-deployment
  # NodePort | ClusterIP
  type: ClusterIP
  ports:
    - name: tm-manager 
      protocol: TCP
      port: 9001
      targetPort: 9001
    # default 8545
    - name: tm-tessera-third-part
      protocol: TCP
      port: 9080
      targetPort: 9080
    # default 8545
    - name: wsrpc-listener
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: quorum-listener
      protocol: TCP
      port: 21000
      targetPort: 21000
    - name: raft
      protocol: TCP
      targetPort: 50401
      port: 50401
    


---
apiVersion: v1
kind: Service
metadata:
  
  name: quorum-node6
  labels:
    app: qubernetes
    tier: backend
    name: quorum-node6
spec:
  selector:
    app: qubernetes
    tier: backend
    name: quorum-node6-deployment
  # NodePort | ClusterIP
  type: ClusterIP
  ports:
    - name: tm-manager 
      protocol: TCP
      port: 9001
      targetPort: 9001
    # default 8545
    - name: tm-tessera-third-part
      protocol: TCP
      port: 9080
      targetPort: 9080
    # default 8545
    - name: wsrpc-listener
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: quorum-listener
      protocol: TCP
      port: 21000
      targetPort: 21000
    - name: raft
      protocol: TCP
      targetPort: 50401
      port: 50401
    


---
apiVersion: v1
kind: Service
metadata:
  
  name: quorum-node7
  labels:
    app: qubernetes
    tier: backend
    name: quorum-node7
spec:
  selector:
    app: qubernetes
    tier: backend
    name: quorum-node7-deployment
  # NodePort | ClusterIP
  type: ClusterIP
  ports:
    - name: tm-manager 
      protocol: TCP
      port: 9001
      targetPort: 9001
    # default 8545
    - name: tm-tessera-third-part
      protocol: TCP
      port: 9080
      targetPort: 9080
    # default 8545
    - name: wsrpc-listener
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: quorum-listener
      protocol: TCP
      port: 21000
      targetPort: 21000
    - name: raft
      protocol: TCP
      targetPort: 50401
      port: 50401
